data:
  raw_processed:
    - VN: 1fo-I97Nm74q-kNsMFTg9GbsenHx0hxSEvyukTFyc1oE
    - TH: 1qrLhWVYME4zSBjDakB4NPZzqeSJIOp6BkFkALvJSYpY
    - PH: 1EalEvFt6IqoV9c6FfxD-ttP9XzFY7HGe2PSglBCYL8U
    - ID: 1Hl7lyD9T01DwzADNo0UYZprvygxSxG-deF_C_aJnu3g
    - MY: 1PWlyYZW0AEf4m_fD-HjLIFllnmOc8OLvZBZcaumhgqA
    - SG: 1leFsFNXDpVQDcgmWycJyDYIBEHqxQnHBs-_0BrOZxEQ
  monthly:
    - VN: 1z1UqgR7xXyCVLIDTS7q2FulcGEjARE_SluQ2JJeUU3M
    - TH: 1OdhUib_BBIxMWLaWp8bAHgAk7VZZAtte15hEU8IRIlY
    - PH: 1f9fHrNBmWnfginZlrCeRKj4UnOZvUcXlzV95hIDdpSA
    - ID: 1RiVIqnGfwHL-uYWVO3rKM9fdYnq6c4Xmx2MkrcFSEcs
    - MY: 1wwakzla9ExrZXhZRZpR6RZ1G6uDg9-VRDIjwZuty-LU
    - SG: 1Q_saSrjJmyOF_HQacyvgOncb2j8_4r2oE_0Ww2aUI00
  agg:
    - VN: 1_hQxJoKr7TLC07dXkASc8cAnHnV0AO0-1G5mf9HZrMM
    - TH: 1Aq6ED1CHGsMXBkdCJl7USE__vrP4OckGpEbgLubXeKs
    - PH: 1LokwEE9ICwxXZkUq3m5Dz-NTb14xwfuXtXias5xiK0E
    - ID: 1EKWMGruXb2stSj47jByrqNAycq3h2x7atKCq5OTM27Y
    - MY: 1xM8iCitvvYvPZm_tnLGhxJdtvlj500eZiEUFgwHfT38
    - SG: 1vWwONBNfwhDGZ32ZYMrkgVODEC9xBgPn5DOXTgOnvwk